version: 2
jobs:     
  test: 
    macos:
      xcode: "10.0" 
    environment:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
    steps:
      - checkout
      - run: sudo gem install bundler --version '<= 1.6.1' && bundle update

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test